name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      push:
        description: 'Push image [true|false]'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Define build args
      run: |
        echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
        BRANCH="${GITHUB_REF#refs/heads/}"
        if [ "$BRANCH" = "main" ]; then
          echo "IMAGE_TAG=latest" >> $GITHUB_ENV
        else
          echo "IMAGE_TAG=$BRANCH" >> $GITHUB_ENV
        fi

    - name: Build & Publish image
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' || github.event.inputs.push == 'true' }}
        tags: ghcr.io/tigattack/patchman:${{ env.IMAGE_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          BUILD_DATE=${{ env.build_date }}
